### ISSUE TITLE
True every time when verify

### ISSUE THREAD

**Issue by blueberry6401** [Levminer/speakeasy#11]
I don't know why this basic function got error.

```
const speakeasy = require('@levminer/speakeasy')
speakeasy.totp.verify({secret: 'FZAFMWDJFQ5DURRTPFWVITBPOJSVIVCJ', token: '000000', encoding: 'base32'})
>> always true, no matter what token you entered
```

**Comment by Levminer** [comment]
Hi!

Thanks for the report! This is a known issue that I can't fix. I'm not the original author of this package.
If you want you can take a look at the code:
https://github.com/Levminer/speakeasy/blob/main/main.js#L178
Or an other issue: #9

**Comment by MyNameIsOka** [comment]
Okay, maybe I didn't understand this correctly but it takes any code for successful verification?
What is the use for this 2FA then?
It wasn't present in the original repo, so why is it not possible to fix?

**Comment by Levminer** [comment]
This, bug was discovered in 2016 https://github.com/speakeasyjs/speakeasy/issues/52

I tried to fix it, but now all codes are verified. I will take a look at his again.

**Comment by Levminer** [comment]
Okay I found the issues, pushing new version.

**Comment by MyNameIsOka** [comment]
wow, thanks a lot! 🙌

**Comment by MyNameIsOka** [comment]
@Levminer , sorry for writing again, but this issue isn't resolved for me.
All codes are still valid for me.
I think the reason is
https://github.com/Levminer/speakeasy/blob/c1a8b4b6043489b5e42407b4340839273b0a6018/main.js#L185-L187
I tested it locally and it works correctly when deleting this part.
What's the reason behind this code part?

**Comment by Levminer** [comment]
Can you paste your code?

**Comment by MyNameIsOka** [comment]
I just deleted those 3 lines.

**Comment by Levminer** [comment]
Yes, I know. I mean the code you are using to generate/verify the 2FA codes.

**Comment by MyNameIsOka** [comment]
Ah sorry, I misunderstood.

The code is basically
1. generate secret on the backend
```
const secret = speakeasy.generateSecret({
    length: 20,
    name: `project123 (${user.id})`,
    issuer: 'project123',
});
```
2. convert `secret.otpauth_url` to QR code via this [library](https://github.com/soldair/node-qrcode) and show user
```
import * as QRCode from 'qrcode';
const createQRCode = async (url: string) => {
    return new Promise<string>((resolve, reject) => {
        QRCode.toDataURL(url, (err, qrcode: string) => {
        if (err) {
            reject(err);
        } else {
            resolve(qrcode);
        }
        });
    });
};
const response = await createQRCode(secret.otpAuthUrl);
```
4. user scans QR code and saves it in e.g. Google Authenticator 
5. user inputs 6 digit code in frontend which is sent to backend
6. backend verifies code with
```
const verified = speakeasy.totp.verify({
      secret: user.MFASecret, // <-- saved in backend database
      encoding: 'base32',
      token: args.token, // <-- sent by user from frontend
});
```

That's the code basically. 
Is that what you meant or is there something else that you had in mind?

**Comment by Levminer** [comment]
Yes, thank you! I will lokk into this later.

**Comment by Levminer** [comment]
Okay, removed those lines, it was there because #9. But now I know the problem

(Fixed in 1.3.3)

**Comment by pozylon** [comment]
Yeah, 123124 still bypasses verify for everything @Levminer @MyNameIsOka

**Comment by Levminer** [comment]
> Yeah, 123124 still bypasses verify no matter what secret @Levminer @MyNameIsOka 

Can you paste your code?

**Comment by Levminer** [comment]
I'm on holiday, I will take a look at this next week!

**Comment by Levminer** [comment]
> I prepared this and found out that, indeed, it seems fixed, it was accountsjs still using the old version 1.3.1 instead of 1.3.3! Really sorry for the scream :) enjoy your holiday @Levminer 
> 
> ```
> import { totp } from '@levminer/speakeasy';
> 
> const result = totp.verify({
>   secret: 'otpauth://totp/SecretKey?secret=OBVUY4TWJJDFMU2EKRJHKQKHIFFVAI25',
>   encoding: 'base32',
>   token: '123124',
>   window: 1,
> })
> 
> console.log({ result });
> ```
> 
> 1.3.3: false
> 1.3.1: true

I'm glad its works. Note to self: there is a typo in the new error message.

**Comment by Kvngstar** [comment]
Thanks for this, i will just have to switch to your package. i am experiencing the same bug while trying to use the original speakeasy package, it  keeps showing false.

**Comment by Levminer** [comment]
> mine keeps showing false is there anything i am doing wrong? @Levminer @blueberry6401 @MyNameIsOka @pozylon
> 
> ```
> const speakeasy = require("@levminer/speakeasy");
> const qrcode = require("qrcode");
> 
> exports.generateQrcode = async () => {
> 	try {
> 		const secretKey = await speakeasy.generateSecret({
> 			length: 20,
> 		}).base32;
> 		const qrcodeUrl = speakeasy.otpauthURL({
> 			secret: secretKey,
> 			label: "socialnetwork",
> 			issuer: "socialnetwork",
> 		});
> 
> 		const urlData = await qrcode.toDataURL(qrcodeUrl);
> 
> 		return { urlData: await urlData, secretKey };
> 	} catch (error) {
> 		throw new Error(error.message);
> 	}
> };
> exports.verifyQrcode = (token, secretKey) => {
> 
> 	return speakeasy.totp.verify({
> 		secret: secretKey,
> 		encoding: "base32",
> 		token: token,
> 		window: 1,
> 	});
> };
> ```
> 
> The secreteKey is stored and retrieved during verification

Two problems that I can think of: 
1. You specified length 20 while generating
2. Window: 1 causes the problem

I'm not realy mainting this package anymore.
