### ISSUE TITLE
What does secret leaking mean?

### ISSUE THREAD

**Issue by pistachiomatt** [Levminer/speakeasy#13]
This library deprecates generating QR codes but it's unclear why. Docs say:

> Do not use to prevent leaking of secret to a third party. Use your own QR code implementation.) Output a Google Authenticator otpauth:// QR code URL.

I was going to use a QR code library on the server, returning the `data:` URI as a JSON response. Does this message say don't do this? Why?

**Comment by Levminer** [comment]
Hi!

I'm not the original author but I think in the past you could use that method to generate a QR code automatically.

Now you should do this:

```js
// generating your codes

let url = speakeasy.otpauthURL({ secret: secret.ascii, label: "Name of Secret", algorithm: "sha512" })

// convert this url to a qr code
```
