### ISSUE TITLE
crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by gecas25** [Levminer/speakeasy#15]
When trying to create TFA QR code I get this error: 

`crypto.randomBytes is not a function
    at Object.generateSecretASCII`

How can I solve this?

**Comment by Levminer** [comment]
I think you are trying to use this library in the browser. The library is only compatible with Node.js

**Comment by gecas25** [comment]
I believe so, but it used to work. 
Maybe you any idea how can I make it work again?

**Comment by Levminer** [comment]
Maybe you used a bundler? Like webpack, webpack polyfills the Node APIs in the browser, so it should work with it.

**Comment by gecas25** [comment]
We are using webpack but it still doesn't work. Maybe I should config something?

**Comment by Levminer** [comment]
If you are on webpack 5 you need: https://www.npmjs.com/package/node-polyfill-webpack-plugin

**Comment by gecas25** [comment]
I am still getting this error: [Vue warn]: Error in created hook (Promise/async): "TypeError: crypto.randomBytes is not a function"

But I am not sure what version of webpack we are using, we use it with Laravel
