### ISSUE TITLE
Uncaught ReferenceError: digest is not defined

### ISSUE THREAD

**Issue by ironmanu** [Levminer/speakeasy#23]
Uncaught reference error when using any of the methods from speakeasy. In my case I just did this: 

`import speakeasy from '@levminer/speakeasy'`
`let token = speakeasy.totp({
    secret: secret.base32,
    encoding: 'base32'
  })`

![Screenshot 2024-03-27 at 13 43 22](https://github.com/Levminer/speakeasy/assets/48432777/b93109f4-6fe9-4f41-8a98-ba416284c2ad)

![image](https://github.com/Levminer/speakeasy/assets/48432777/ba00d28d-bda8-426c-86f4-802df8cfe475)

Im using vue 3.4.15

**Comment by Levminer** [comment]
This library uses Node.js modules, it can't be used in the browser. Or you can try using polyfills.
